### ISSUE TITLE
Rebuild snap to work with worktrees

### ISSUE THREAD

**Issue by rcj4747** [philroche/lpshipit#2]
It feels wrong to open this here but there is no way to open issues on snapcraft.io.  Upstream GitPython has added support for [worktrees](https://github.com/gitpython-developers/GitPython/commit/aec58a9d386d4199374139cd1fc466826ac3d2cf) and a rebuild of the snap will allow me to do this...

```
git clone somerepo foo
cd foo
git worktree add master ../bar
cd ../bar
lpshipit (and specify bar as the git repository)
```

Currently, specifying the worktree as the git repository directory with lpshipit version 0.1 rev 19 produces:
```
$ lpshipit
Retrieving Merge Proposals from Launchpad...
Traceback (most recent call last):
  File "/snap/lpshipit/19/./bin/lpshipit", line 11, in <module>
    load_entry_point('lpshipit==0.1', 'console_scripts', 'lpshipit')()
  File "/snap/lpshipit/19/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/lpshipit.py", line 341, in lpshipit
    loop.run()
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/lpshipit.py", line 326, in keypress
    directory_chosen(chosen_directory)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/lpshipit.py", line 291, in directory_chosen
    repo = git.Repo(directory)
  File "/snap/lpshipit/19/lib/python3.5/site-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: bar
```

**Comment by philroche** [comment]
Build now in progress
