### ISSUE TITLE
Rebuild snap incorporating new GitPython

### ISSUE THREAD

**Issue by OddBloke** [philroche/lpshipit#4]
As per https://github.com/gitpython-developers/GitPython/issues/687, the version of GitPython shipped in the snap doesn't work with recent versions of git (one of which is now in bionic).  This leads to the following traceback:

```pytb
Traceback (most recent call last):
  File "/snap/lpshipit/24/./bin/lpshipit", line 11, in <module>
    load_entry_point('lpshipit==0.1', 'console_scripts', 'lpshipit')()
  File "/snap/lpshipit/24/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/lpshipit.py", line 341, in lpshipit
    loop.run()
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/snap/lpshipit/24/lib/python3.5/site-packages/lpshipit.py", line 144, in mp_chosen
    local_branches = [branch.name for branch in repo.branches]
  File "/snap/lpshipit/24/lib/python3.5/site-packages/git/repo/base.py", line 267, in heads
    return Head.list_items(self)
  File "/snap/lpshipit/24/lib/python3.5/site-packages/git/util.py", line 942, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/snap/lpshipit/24/lib/python3.5/site-packages/git/refs/symbolic.py", line 609, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/snap/lpshipit/24/lib/python3.5/site-packages/git/refs/symbolic.py", line 100, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

**Comment by philroche** [comment]
Thanks for the report. It has now been rebuilt, tested in bioinc and released to stable channel.

`sudo snap refresh lpshipit`  will get you the new version.

**Comment by OddBloke** [comment]
Thanks!
