### ISSUE TITLE
Traceback in `summarize_mps`

### ISSUE THREAD

**Issue by OddBloke** [philroche/lpshipit#5]
```
Retrieving Merge Proposals from Launchpad...
Traceback (most recent call last):
  File "/snap/lpshipit/36/./bin/lpshipit", line 11, in <module>
    load_entry_point('lpshipit==0.1', 'console_scripts', 'lpshipit')()
  File "/snap/lpshipit/36/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/lpshipit/36/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/lpshipit/36/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/lpshipit/36/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/lpshipit/36/lib/python3.5/site-packages/lpshipit.py", line 129, in lpshipit
    mp_summaries = summarize_mps(mps)
  File "/snap/lpshipit/36/lib/python3.5/site-packages/lpshipit.py", line 72, in summarize_mps
    else commit_message.splitlines()[0]
IndexError: list index out of range
```

**Comment by OddBloke** [comment]
I can't reproduce this when not using the snap. :sob:

**Comment by philroche** [comment]
36 seems old. Have you tried a snap refresh?

**Comment by OddBloke** [comment]
It's the latest from where I'm sitting:

```
name:      lpshipit
summary:   Helpful utility for merging launchpad MPs (only works for git
repos)
publisher: philroche
license:   unknown
description: |
  Helpful utility for merging launchpad MPs (only works for git repos)
commands:
  - lpshipit.lpmpmessage
  - lpshipit
snap-id:   tb6rOC4Li05c2iVJqBMjjnyL1yXbdpNG
tracking:  stable
refreshed: 2018-04-24T11:11:57-04:00
installed:   0.1 (36) 30MB classic
channels:
  stable:    0.1 (36) 30MB classic
  candidate: ↑
  beta:      ↑
  edge:      0.1 (36) 30MB classic
```
