### ISSUE TITLE
Traceback when running lpmpmessage

### ISSUE THREAD

**Issue by OddBloke** [philroche/lpshipit#8]
```
Retrieving Merge Proposals from Launchpad...
Traceback (most recent call last):
  File "/snap/lpshipit/47/./bin/lpmpmessage", line 11, in <module>
    load_entry_point('lpshipit==0.1', 'console_scripts', 'lpmpmessage')()
  File "/snap/lpshipit/47/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/lpmpmessage.py", line 158, in lpmpmessage
    loop.run()
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/listbox.py", line 999, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/wimp.py", line 540, in keypress
    self._emit('click')
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/widget.py", line 460, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/snap/lpshipit/47/lib/python3.5/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/snap/lpshipit/47/lib/python3.5/site-packages/lpmpmessage.py", line 142, in mp_chosen
    'description'],
KeyError: 'description'
```

**Comment by OddBloke** [comment]
This has not been my day.

**Comment by philroche** [comment]
My bad.

**Comment by OddBloke** [comment]
I'm on it.

**Comment by philroche** [comment]
Now fixed
